AllCops:
  Exclude:
    - bit_player.gemspec
    - Rakefile
    - bin/**/*
    - db/**/*
    - lib/**/*
    - spec/dummy/**/*

AccessorMethodName:
  Enabled: false

Documentation:
  Exclude:
    - db/**/*
    - spec/**/*

IfUnlessModifier:
  Enabled: false

LineLength:
  Exclude:
    - db/**/*

MethodLength:
  Exclude:
    - db/**/*

StringLiterals:
  EnforcedStyle: double_quotes

TrivialAccessors:
  Enabled: false

WordArray:
  Enabled: false
