inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - gemfiles/**/*
    - spec/dummy/**/*
    - vendor/**/*
    - Rakefile
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

AbcSize:
  Max: 20

AccessorMethodName:
  Exclude:
    - app/**/*

Documentation:
  Exclude:
    - spec/**/*

MethodLength:
  Max: 20

PredicateName:
  Exclude:
    - spec/**/*

StringLiterals:
  EnforcedStyle: double_quotes

TrivialAccessors:
  Exclude:
    - app/**/*
