AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - spec/dummy/**/*
    - vendor/**/*
    - Rakefile

AccessorMethodName:
  Exclude:
    - app/**/*

Documentation:
  Exclude:
    - spec/**/*

MethodLength:
  Max: 20

PredicateName:
  Exclude:
    - spec/**/*

StringLiterals:
  EnforcedStyle: double_quotes

TrivialAccessors:
  Exclude:
    - app/**/*
